// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxybh7GIiMwuwus2Q5RF39s7rcs-Ae7ZE',
    appId: '1:84884898984:web:b405cb06be5089e339ae9d',
    messagingSenderId: '84884898984',
    projectId: 'afsgpt',
    authDomain: 'afsgpt.firebaseapp.com',
    storageBucket: 'afsgpt.appspot.com',
    measurementId: 'G-MSMCFG8H07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmgxkCnXs16u33t8Ld9FaaVxhrpA4WXM',
    appId: '1:84884898984:android:a5c21a896a2cb78c39ae9d',
    messagingSenderId: '84884898984',
    projectId: 'afsgpt',
    storageBucket: 'afsgpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQNUBgDbvjfClY6YkjU6H_sz-v-BWV6DQ',
    appId: '1:84884898984:ios:90ca09761b3144b539ae9d',
    messagingSenderId: '84884898984',
    projectId: 'afsgpt',
    storageBucket: 'afsgpt.appspot.com',
    iosBundleId: 'com.example.afsGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQNUBgDbvjfClY6YkjU6H_sz-v-BWV6DQ',
    appId: '1:84884898984:ios:90ca09761b3144b539ae9d',
    messagingSenderId: '84884898984',
    projectId: 'afsgpt',
    storageBucket: 'afsgpt.appspot.com',
    iosBundleId: 'com.example.afsGpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxybh7GIiMwuwus2Q5RF39s7rcs-Ae7ZE',
    appId: '1:84884898984:web:8abe82ada53e019239ae9d',
    messagingSenderId: '84884898984',
    projectId: 'afsgpt',
    authDomain: 'afsgpt.firebaseapp.com',
    storageBucket: 'afsgpt.appspot.com',
    measurementId: 'G-YBZM5WZV4H',
  );

}